### ISSUE TITLE
About useing docker run the program

### ISSUE THREAD

**Issue by ghost** [odan/slim4-tutorial#18]
I want to know how to run the starter template program in docker?

Because I try to copy your second repositories "slim4-skeleton" dockerfile and docker-compose.yml file, then run it will fail.

Thanks.

<img width="1278" alt="err" src="https://user-images.githubusercontent.com/44782630/103441650-60e8cf00-4c8a-11eb-8b5a-fcef422e046b.png">

**Comment by odan** [comment]
The composer autoloader is missing.

**Comment by ghost** [comment]
Got it. thanks
