### ISSUE TITLE
bought the book, can i ask for crypt password?

### ISSUE THREAD

**Issue by peppeg85** [odan/slim4-tutorial#19]
hello, i'm new to php,i bought the ebook, it is well done, but i didn't find any hashing password functionality,  how can i add it in slim4? what are the best practicies? where to store the seed?
thank you

**Comment by odan** [comment]
Hi @peppeg85 Thanks for your support! 

This particular topic is not covered in the eBook. I will use this as inspiration for a new article.

In PHP generally, it's good practice to use the [password_hash](https://www.php.net/manual/en/function.password-hash.php) to create a password hash and the [password_verify](https://www.php.net/manual/en/function.password-verify.php) function to verify that a password matches a hash. You can store that hash directly in the database, for example in a users table within the password field. The integration into a Slim project depends on your specific use-case. You could, for example, create a [UserAuth](https://github.com/odan/slim4-skeleton/blob/master/src/Domain/User/Service/UserAuth.php#L42) class with a `authenticate(string $username, string $password)` method that uses the `password_verify` function to check the users credentials at login time.

**Comment by peppeg85** [comment]
ok, thanks for the fast response...just another question to understand what is a good practice to organize the files, before the insert of a new user, if i want to check if the email exists, what is the best practice (also compliant with the structure of your project)? 
i should to create an action inside the  Action folder named "UserCheckIfExist" OR inside the UserCreator service with a new public function "checkemail(string $email)" thah checks the email in db (so with a function inside UserCreatorRepository that selects the user with email)

thankl you!

**Comment by odan** [comment]
I don't know your specific use-case from the the UI perspective or from the API client to give here a correct answer.

The most common way would be to create an endpoint for `POST /users` and a corresponding Action class (e.g. [UserCreateAction](https://github.com/odan/slim4-skeleton/blob/master/src/Action/User/UserCreateAction.php)) to handle this HTTP specific request. The `UserCreateAction` just invokes the use-case specific (application) Service e.g. [UserCreator](https://github.com/odan/slim4-skeleton/blob/master/src/Domain/User/Service/UserCreator.php). The method name could be `createUser`. The `createUser` method then validates the input, e.g. checks for an existing email address using a Repository to read from the database. If the validation fails a `ValidationExcpetion` should be thrown.

You can find some examples in the [Slim 4 Skeleton project](https://github.com/odan/slim4-skeleton).

The eBook also includes a section about "Action Domain Responders", which explains this concept more in detail.

**Comment by peppeg85** [comment]
ok!! thanks for your support!
