### ISSUE TITLE
Callable App\Action\HomeAction does not exist

### ISSUE THREAD

**Issue by timoheld** [odan/slim4-tutorial#2]
Hi, i have a problem with the Home controller.
![image](https://user-images.githubusercontent.com/60256244/85826856-4edf1e80-b785-11ea-8e4f-6a7435522543.png)

**This is my directory structure:**
.
|- Action (here is the HomeAction Controller)
|- config (here is the hole config -> bootstrap.php, container.php, middleware.php, routs.php and settings.php)
|- public (Document Root with the index.php and the htaccess)
|- vendor 
|- composer.json
|- composer.lock
|- composer.setup.php

**This is my HomeAction.php**

```
<?php

namespace App\Action;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

final class HomeAction
{
    public function __invoke(
        ServerRequestInterface $request, 
        ResponseInterface $response
    ): ResponseInterface {
        $response->getBody()->write('Hello, World!');
        return $response;
    }
}
```

This is my routes.php

```
use Slim\App;

return function (App $app) {

    $app->get('/', \App\Action\HomeAction::class);
    
};
```

**bootstrap.php**

```
<?php

use DI\ContainerBuilder;
use Slim\App;

require_once __DIR__ . '/../vendor/autoload.php';

$containerBuilder = new ContainerBuilder();

$containerBuilder->addDefinitions(__DIR__ . '/container.php');

$container = $containerBuilder->build();

$app = $container->get(App::class);

(require __DIR__ . '/routes.php')($app);

(require __DIR__ . '/middleware.php')($app);


return $app;
```

**middleware.php**

```
<?php

use Selective\BasePath\BasePathMiddleware;
use Slim\App;
use Slim\Middleware\ErrorMiddleware;

return function (App $app) {
    $app->addBodyParsingMiddleware();

    $app->addRoutingMiddleware();

    $app->add(BasePathMiddleware::class);

    $app->add(ErrorMiddleware::class);

};
```

**composer.json**

```
{

    "require": {
        "akrabat/rka-content-type-renderer": "^1.0",
        "php-di/php-di": "^6.2",
        "selective/basepath": "^1.0",
        "slim/psr7": "^1.1",
        "slim/slim": "4.*",
        "symfony/yaml": "^5.1",
        "zircote/swagger-php": "^3.0"
    },
    "autoload": {
      "psr-4": {
        "App\\": "app/"
      }
    },
    "autoload-dev": {
      "psr-4": {
        "App\\Test\\": "tests/"
      }
    },
    "config": {
      "process-timeout": 0,
      "sort-packages": true
    }
}
```

Can someone help me?

**Comment by odan** [comment]
Hi @timoheld 

Your directory structure goes not conform with your composer.json autoloader settings. 
Usually all the PHP files goes into the src/ directory. [Read more](https://github.com/php-pds/skeleton).

But it looks like you are storing the PHP action classes under `{project}/Action/` and not under `{project}/src/Action`.
This could be problematic in the long run.

You also point the App namespace to `app/` in composer.json. This directory does not exists.

**Comment by timoheld** [comment]
Hi @odan 
Thanks for your help. Now it works.
