### ISSUE TITLE
PhpSession: "Headers already sent" warning when testing

### ISSUE THREAD

**Issue by samuelgfeller** [odan/slim4-tutorial#23]
I get the following warning when doing this test (simple action that only renders a template):
```php
public function testXAction(): void
{
    $request = $this->createRequest('GET', $this->urlFor('x-page'));
    $response = $this->app->handle($request);
    self::assertSame(StatusCodeInterface::STATUS_FOUND, $response->getStatusCode());
}
```
Warning: 
```
Warning ini_set(): Headers already sent. You cannot change the session module's ini settings at this time on line 257 
in file vendor\odan\session\src\PhpSession.php
```
In my container I declare the `SessionInterface` with `$session->setOptions((array)$settings['session']);` and `setOption()` changes ini settings but can't because "Headers already sent".  
This happens as far as I know when trying to change them *after* something is outputted. There should be no ouput though and I can't find where. I tried `ob_start();` in the test bootstrap and then `ob_get_clean();` right before `$session->setOptions(/*...*/)` but output is an empty string (no whitespace).  

1. The issue is "fixed" when I add `ob_start();` in the test bootsrap or `<phpunit stderr="true">` in `phpunit.xml` but is it the way to go? I would really like to understand the issue rather than just outputting in another channel. It feels like a dirty workaround like [he](https://stackoverflow.com/a/34273310/9013718) says. 
Why does it not happen when I load the page normally (not testing)?
2. How do I debug this? I would really like to understand what is going on.
3. To even see the error message I had to re-enable logging for testing which is not a workaround that I like. How can I configure my `DefaultErrorHandler.php` and or PHPStorm to show the error message (in this case "Headers already sent") in the [ouput pane](https://www.jetbrains.com/help/phpstorm/test-runner-tab.html)?

**Comment by odan** [comment]
This is a typical issue that can happen when you use the "real" session handler for testing and somewhere in the tested codebase a error/warning/notice occurs, e.g. undefined array index etc. Then this error/warning/notice message will be sent directly to the PHP output buffer. The session module is then not able to handle the response headers, because the output buffer with the error message has been flushed already. Yes, it's not good practice to use `ob_start` to fix this issue.

When you run the tests within PhpStorm or from the console, you should to see the detailed error message from the buffer. 

For testing purpose the "best" solution would be to use a in-memory Session handler, e.g. [Odan\Session\MemorySession](https://odan.github.io/session/v5/#memory-session) when running tests.

You can configure this `MemorySession` within the environment settings, or you set the MemorySession instance directly into the DI container of your phpunit `setUp` method.

**Comment by samuelgfeller** [comment]
>  somewhere in the tested codebase a error/warning/notice occurs
> Then this error/warning/notice message will be sent directly to the PHP output buffer

How can I find out what this error is? It doesn't show up in the output pane, logs created with my `DefaultErrorHandler` or even `apache/error.log`. The only error is the "Headers already sent" see [this screenshot](https://i.imgur.com/9U84esH.png).

> For testing purpose the "best" solution would be to use a in-memory Session handler, e.g. Odan\Session\MemorySession when running tests.

I added it in the testing container and the issue does not appear anymore, but neither does any other in any logger nor the output pane see [here](https://i.imgur.com/y0SwPQu.png). I don't understand what output caused the Session config to fail. 

> You can configure this MemorySession within the environment settings

How would you do this?

**Comment by odan** [comment]
First ensure that phpstan shows no error, run `composer phpstan`. Then you could try to set a debugger breakpoint in the `RegisterAction` class and debug it. You will find the exact line and Exception details very quickly with Xdebug. As a quick fix you could also just disable the Slim ErrorMiddleware. But the debugger (Xdebug) would be the best option.

![image](https://user-images.githubusercontent.com/781074/107918620-50569480-6f6a-11eb-81f1-8ba3189b6983.png)

**Comment by samuelgfeller** [comment]
Well I have a hard time understanding xdebug this time. Here is a gif of when the error is thrown. It seems that the error only occurs when resolving the `SessionInterface` and not before. On the other hand, there could be a notice / warning but then it should log in the default `apache/error.log` which it didn't (well it did not log the "Headers already set" either so I suppose that xdebug doesn't log when testing but then it should be displayed in the ouput pane which it didnt.) 
![Debug gif](https://i.imgur.com/HFRSFe7.gif) 
An error message would help me greatly. I tried to disable `ErrorMiddleware` but the same error is just outputted to the output pane [screenshot](https://i.imgur.com/iMAn70C.png). 

Unrelated question: I want the error to be shown in the output pane when testing like when disabling the slim `ErrorMiddleware` and my `DefaultErrorHandler` on the screenshot. How can I configure the test env (probably changing `DefaultErrorHandler`) to behave like this?

**Comment by odan** [comment]
It looks like the PhpSession handler is still being used in the test environment.

Make sure to set the `Odan\Session\MemorySession` handler into the test container for the SessionInterface before the first test starts.

```php
use Odan\Session\MemorySession;
use Odan\Session\SessionInterface;
$session = new MemorySession();

$session->setOptions([
    'name' => 'app',
]);

$this->container->set(SessionInterface::class, $session)
```

 If you have trouble with the `container->set(...)` method you may try to load the settings from an environment specific settings array.

Let only the `SessionMiddleware` start the session. Search in your codebase for `session_start` and remove it. 

```php
use Odan\Session\Middleware\SessionMiddleware;

// ...
$app->add(SessionMiddleware::class);
```

PS: If you still want to use the PhpSession class, you can also try to tear down the previous session as well: See [SessionTestTrait](https://github.com/odan/slim4-skeleton/blob/1926400303907881dff88ffe2ca8e1df69f8e993/tests/Traits/SessionTestTrait.php)
But then you have to use `ob_start`, which is not so good.

Usage:

```php
public function tearDown(): void
{
    $this->tearDownSession();
}
```

**Comment by samuelgfeller** [comment]
Oh I'm sorry for the confusion I wasn't clear in my wording. I added it in the testing container and the issue did not appear anymore ([image](https://i.imgur.com/y0SwPQu.png)) so MemorySession worked great. 

I reverted the fix because I wanted to understand what was going on. Theoretically it *should* work with the normal `PhpSession` because before resolving things in the container nothing should be outputted; `ini_set` should work.  

To know that there are certain issues that I can't debug with my current knowledge makes me uncomfortable. What if something happens in production where potential clients depend on a quick fix, but I'm clueless because I can't find the error?   
In my learning phase now I want to learn as much as possible to be ready for the "real world". Those types of issues are great to be even more prepared. 
That's also why I asked those somewhat unrelated questions, I don't only want to fix this specific issue; I want to learn everything around it, so I know better what steps to take next time.   

The issue is fixed however, and I don't want to use more of your time. I have the feeling that I say it too often but genuinely thank you, again.

**Comment by samuelgfeller** [comment]
To be able to see exception details nicely in the output pane while testing when using a custom error handler, the following did it for me in `DefaultErrorHandler.php`: 
```php
// Error output if script is called via cli (e.g. testing)
if (PHP_SAPI === 'cli') {
    // The exception is thrown to have the default behaviour
    throw $exception;
}
```
