### ISSUE TITLE
Slim4 Session

### ISSUE THREAD

**Issue by Advikilaiya** [odan/slim4-tutorial#24]
Hello Sir,
I have followed  your slim4-tutorial,its working fine. but session data not able to get.  
$this->session->set('user', $user); 
but not able to get  $this->session->set('user'); on another url.
Session not recognized globally

Can you guide me?

**Comment by odan** [comment]
Hi @Advikilaiya You should add more details. 

> but not able to get $this->session->set('user'); on another url.

The `set` method just sets a value into a session. Have you tried using the `get` method?

```php
$user = $this->session->get('user');
```

**Comment by Advikilaiya** [comment]
Yes. in login page  $this->session->set('user'); so try to get session value as $this->session->get('user');  on home page. but that session no at all getting index page. I have followed as you given Slim4 Session reference

**Comment by odan** [comment]
> $this->session->set('user');

This will just set nothing, resp. `null`. You have to provide a value for the key, e.g.

```php
$this->session->set('user', $user);
```

Please consult the [documentation](https://odan.github.io/session/v5/#methods).
