### ISSUE TITLE
API JSON response instead of "throwing" exceptions

### ISSUE THREAD

**Issue by mapicard** [odan/slim4-tutorial#25]
Hi,
Following your tutorial for an API implementation, you are using `throw new ValidationException('Please check your input', $errors);`. I like the idea of having a central place for error/exception handling but I would perfer to send a json response back to the api client. How would you integrate it in this tutorial ?
Thank you.

**Comment by odan** [comment]
If you like this notification pattern for validation, I recommend having a look at this library: [selective/validation](https://github.com/selective-php/validation). 

The `ValidationExceptionMiddleware` catches the `ValidationException` at a central place and converts it into a nice JSON response. 

[Read more](https://github.com/selective-php/validation#slim-4-integration)

**Comment by mapicard** [comment]
Thanks again for your reply. I had seen your note about [selective/validation](https://github.com/selective-php/validation) but I thought this was only for validation exception and was just gonna return 422. I was more thinking of a general exception catcher that I could call with a message, a returnCode and extra data object. I will definitely look again and Read more.

**Comment by odan** [comment]
This is correct, this middleware handles only ValidationException's. To handle more general exceptions, you could configure the Slim internal ErrorHandler or you add your own ExceptionMiddleware to the middleware stack.

* https://www.slimframework.com/docs/v4/middleware/error-handling.html
* https://odan.github.io/2020/05/27/slim4-error-handling.html
