### ISSUE TITLE
Message: Callable BasePathMiddleware does not exist

### ISSUE THREAD

**Issue by LucianoPaulista** [odan/slim4-tutorial#27]
After following the tutorial I am getting the following error: Type: RuntimeException
Code: 0
Message: Callable BasePathMiddleware does not exist
File: C: \ xampp \ htdocs \ slim4php \ vendor \ slim \ slim \ Slim \ CallableResolver.php
Line: 147

when trying to display hello world.

**Comment by odan** [comment]
Have you added the use statement at the top of the php file?

```php
use Selective\BasePath\BasePathMiddleware;
```

Also try to run `composer update` to fix it.

**Comment by LucianoPaulista** [comment]
Hello odan it was that I had forgotten to add the `use Selective\BasePath\BasePathMiddleware` in the middleware.php file I'm sorry for the inconvenience and for the English I speak from Brazil thanks for your attention !!!
