### ISSUE TITLE
Too few arguments to function App\Exception\ValidationException::__construct()

### ISSUE THREAD

**Issue by vincentschweitzer** [odan/slim4-tutorial#3]
Hi,
 When call on user creation is : 

curl "http://slim.test/users"  -X POST -d "{\n  \"username\": \"john.doe2\",\n  \"first_name\": \"John\",\n  \"last_name\": \"Doe\",\n  \"email\": \"john.doeexample.com\"\n}" -H "Content-Type: application/json" 

It should go into ValidationException (email is not valid), but only 2 arguments are given to ValidationException and 4 are expected

**Comment by odan** [comment]
Indeed. The default values where missing. It should be fixed now.
