### ISSUE TITLE
Should repository load associated objects by default

### ISSUE THREAD

**Issue by samuelgfeller** [odan/slim4-tutorial#32]
I'm faced with a little dilemma here and am curious about your approach on this.

In my example app, users can create posts linked by `user_id` in the post table. Now when I retrieve posts from the db, the linked user information is almost always needed, so I've created a function that adds the full `User` object to the `Post` DTO (get user by `user_id` fk from db and populate the `User` attribute of the `Post` object).

Now besides this being hard and inefficient to unit test, when expanding (objects with more attributes and more foreign keys) it's not very realistic to have a function for every different foreign key. I was asking myself if you would recommend (and if its good practice) to do the following:  
When retrieving a dataset from the db they are instantiated in the repository. **How about populating the instance that will be returned by the repository (`Post`) with all its linked attributes full objects (`User`) rather than just fk value (`user_id`) ?**  

I've worked a tiny bit with Symfony and Doctrine before and if I recall correctly it is done automatically there. I could access linked object details from the entity returned by the ORM without having to get the rows separately by fk.

If you do recommend it, how'd you do it? Because on larger classes that could mean a lot more queries. That's why I asked myself if it's not more efficient to directly do `LEFT JOIN`s for every linked table and then hydrate everything from there. That would be only one query. It would be great to have a generic function like the `hydrate` helper you recently made but adapted to populate the associated classes too.

**Comment by odan** [comment]
I guess there is a little confusion about ORM's and Repositories.

There are two typed of Repositories:

### Collection-Oriented Repositories

DDD advocates for Collection-Oriented Repositories. Using this pattern makes most sense when you also 
use it in combination with the [Unit of Work](https://martinfowler.com/eaaCatalog/unitOfWork.html) pattern.

### Persistence-Oriented Repository

There are times when collection-oriented Repositories don't fit well with our persistence mechanism. If you don't have a unit of work, keeping track of Aggregate changes is a difficult task. 

Repositories often use the [Data Mapper pattern](https://designpatternsphp.readthedocs.io/de/latest/Structural/DataMapper/README.html) to translate between representations. 

Therefore, use the Repository pattern that fits to your specific needs. 

I would recommend thinking in terms of "use cases" and I would try to build the services and repositories for each specific use case. In other words, you build repositories with "use case specific queries", even using 'LEFT / INNER JOIN' to fetch only the data you need and reduce the number of queries to a minimum.

Depending on the complexity, you may also need to run multiple queries using different repository methods. Within a service it is also possible to collect different items from different sources of the database (using repositories) and combine them into a completely new object. This means that you define the relationships per query (using `JOIN`) when they are really needed, and not per entity or table.

**Comment by odan** [comment]
PS: If you want, we can talk on Skype (or Discord) about this topic.

**Comment by samuelgfeller** [comment]
Indeed, I don't want to mix generic ORM behaviour with Repositories. I'll make the examples with Posts and Users again to see if I got it right. 
`findAllPosts()` (used to display all posts to all users) or `findPostsByUserId` (when filtering posts by user) or even `findPostById` (form value when user wants to edit a post). 
Now if I understand your suggestion correctly, you'd do more something like this: 
Design functions/services and repositories by use case, meaning that if I need to display all posts and for this use case I need user info, I implement a repository function `findAllPostsWithUser` that makes a select query on the post table with a join on users and instantiates a `Post` (dto) object with loaded `User` attribute*. Not blindly loading every single linked table that could lead to a huge aggregate of objects. Makes sense to me. 

*Here is the question if we make this function that **may** be used by other use cases, so we retrieve and load all user values OR really tied to this specific use case and this repo function only selects the values `first_name` and `last_name` from joined user table because to display all posts only the name is needed (`findAllPostsWithUserName`). And if there is another use case that needs the email address, then a new repo function is created like `findAllPostsWithUserEmail. Or is the first a compromise you'd do?)

> PS: If you want, we can talk on Skype (or Discord) about this topic.

I mean, sure! I'd love to. I have to admit that I didn't understand of the two types of repositories, how unit of work look like in practice and how Data mapper pattern makes sense.  
Actually I had planned since quite some time to ask you for a call. Since February, I write down little question that aren't urgent to look at and some things I want you to review and give me your opinion, but I thought that I'd ask you at the end of my example project, so we can go through everything at once (naturally I'd pay you accordingly for this service that is very valuable to me).
But for now, if there is more to discuss about this specific topic I would gladly do that on Skype or else. I still didn't comprehend the patterns you mentioned really. [Here](https://join.skype.com/invite/iz9KtEduzPH4) is my Skype link. Best timing for me would be Monday to Friday from 8am to 5pm with little exceptions, but I can easily adapt to your availabilities.

**Comment by odan** [comment]
Every Domain class has its own "bounded context" and can be placed in a specific namespace and sub-namespace.
For example, you have a use case to retrieve all User posts you could create classes like this:

```
src/Domain/Blog/Service/UserBlogFinder.php
src/Domain/Blog/Repository/UserBlogFinderRepository.php
```

For another use case you have another specific Service and Repository class. 

```
src/Domain/Book/Service/BookFinder.php
src/Domain/Book/Repository/BookFinderRepository.php
```

You see, each Service can have no, one or multiple Repositories as dependency. 
Sometimes a Service can use multiple Repositories too. As long as they are in the same bounded context (sub-domain / namespace).

All the Repositories I show here are technically "just" [Data Mapper](https://designpatternsphp.readthedocs.io/en/latest/Structural/DataMapper/README.html).

**Comment by samuelgfeller** [comment]
Ah, I see now what is meant with Data Mapper. 

I see this being manageable for small to maybe light medium apps but if it gets a bit larger wouldn't that result in LOTS of classes and trickier to keep an overview? 
I assume that given your experience also with larger projects and recommendation I already know your response, but I'd gladly take some advice on how to navigate with so many files. Do you use `CTRL + N` a lot, and is that indeed easier than methods? I'm sure the project-wide "search and replace" important as well. 

The second thing is about code (almost) duplicates. I know less code has to be loaded if every class contains ONLY the things needed for this specific use case **for each request** and its ideal for smaller projects that need to be very performant and fast but overall, wouldn't that make a lot more code in general, often duplicates with small changes and harden refactoring? For instance when there is a new row in the posts table that is needed in almost every use case I'd have to adapt the select queries of each class or if a table row name changes I'd have to go through all classes that use this row and that's overall a lot more files. I assume that refactoring would be easier if functions were in the same repository class, or how do you feel about that? 

As an example, now in my general `PostRepository` I put the array with the relevant user rows in an attribute and use them in the repo functions (that do need those user rows) with `$this->userRows` and if someday there is one relevant user row more I'd only have to adapt this attribute and if it's in every use case repository class they each contain a list of the relevant user rows and if they happen to be the same (which is most of the case) its "duplicated". To change them, I'd have to go through each class. 
This very example is not important, it's just to illustrate what my concern is. Obviously not only bound to this example or even repositories. I know that for this case I could simply use project wide search and replace, but I couldn't think of a better example.

Probably I'm wrong, and it's the opposite, but I have to ask this as its always in the back of my mind and due to my lack of experience I don't actually know how it is otherwise.
And to be clear I'm not at all arguing about whether this approach is good or not. I'm convinced it's good, and I want to adopt it because it makes sense. I'm just curious about how you handle those two things and how you see them. I'd like to have another viewpoint especially from someone that (I assume) has worked with this method on larger projects.

**Comment by odan** [comment]
> I see this being manageable for small to maybe light medium apps

Everything I recommend applies to small AND very big projects.

> but if it gets a bit larger wouldn't that result in LOTS of classes 

Yes, you get more classes, but exactly this is the result when you focus the responsibility of a class to only one specific task.
You should not be afraid of many classes, but of classes that are too big.

> and trickier to keep an overview?

No, it's much easier to handle and test smaller classes then big god classes.

The key point of this pattern is, unlike the **[ORM Active Record Anti-pattern](https://www.mehdi-khalili.com/orm-anti-patterns-part-1-active-record)**, the data model follows Single Responsibility Principle.

In practice, I open submodule / namespace and I see all the classes that belongs together. We have discussed this already.
As you mentioned, yes I also use `CTRL + N` sometimes, but I don't see a problem with this in my daily business. 

> The second thing is about code (almost) duplicates.

I hear this (wrong) assumption every time from people that worked with a classic ORM like Doctrine.
In real life you nearly never have one use case that is exactly the same. So on code level you never have exactly the same logic and query when you watch at your classes/modules  from a process perspective.

 >  ...often duplicates with small changes and harden refactoring?

I'ts the opposite. It's much easier to refactor tiny classes than big (god) classes. When you have small specialized classes, the risk that you break something in another part of the application is much smaller. If our module performs one task and nothing else or has a clear purpose, our module has high cohesion. On the other hand, if our module tries to encapsulate more than one purpose or has an unclear purpose, our module has low cohesion. So, cohesion focuses on how a single module/class is designed. Higher the cohensiveness of the module/class, better is the OO design.

When you rename a column, you have to refactor the code anyway, regardless of whether you use an ORM or repository (data mapper). Renaming a field usually doesn't happen very often and tests should cover that, of course.

Try all the different concepts and find the way that works best for you and your team. Personally, I don't use ORM anymore because I now abstract all data accesses via Repositories.

**Comment by samuelgfeller** [comment]
> No, it's much easier to handle and test smaller classes then big god classes. 

That's so interesting I'm almost thrilled to see this in production in larger projects. I only knew the big classes and that will be a big shift (I'm looking forward to).

> In practice, I open submodule / namespace and I see all the classes that belongs together

Makes sense. Categorizing everything in submodules / namespaces makes a better overview than function names.

> In real life you nearly never have one use case that is exactly the same. 

Glad to hear that this assumption is wrong. 

> When you rename a column, you have to refactor the code anyway, regardless of whether you use an ORM or repository (data mapper)

Yes my last point was about general changes not use case specific change (which is logically easier if there is high cohesion). But as you said those changes don't often happen, so the benefits are much greater. Would be maybe a bit different if big general changes happen all the time, but they don't.  

> Personally, I don't use ORM anymore because I now abstract all data accesses via Repositories.

This and the trend to only use libraries that are absolutely needed keeping things light and optimized as well as working with a microframework are the reasons I like your working methodology so much. 
After being told so many times that if I want to do a bigger project I would have to use big frameworks otherwise I'd reinvent the wheel it's so good to see someone experienced actually recommending lighter tools and not use a library or something "pre made" for every single thing. Keeping things simple and light. 

I'll close this issue for now but as I'm about to make big changes to my code I'm sure more questions will come, is it OK if I just comment them here? Or I write a collection of questions about this topic, and we once do a call to clarify things.

**Comment by samuelgfeller** [comment]
Edit: Question now moved to #33

**Comment by odan** [comment]
Please create a new issue.

**Comment by samuelgfeller** [comment]
Sure. Done. https://github.com/odan/slim4-tutorial/issues/33
