### ISSUE TITLE
How to instantiate an associated object from the fetched result of a join query

### ISSUE THREAD

**Issue by samuelgfeller** [odan/slim4-tutorial#33]
The fetched `'assoc'` result of the `cake/database` query is an array with the col name as key and col value as value which is fine, but now I have the following "issue".
1. I don't know from which table the column and its value is ([I asked here](https://stackoverflow.com/questions/67505987/get-fetched-result-in-different-arrays-by-joined-tables) if there would be a way to group them by table, but it doesn't seem to be the case) 
2. If there is the column name twice in different tables, only the last one is actually present in the fetched array.

Now I could "solve" both of these issues by always defining each column every time and give all of them an alias (not necessarily something I wanted as for the `post` case I want all post values and only a few from users, and I'd have to define and alias every post column now which is more code and more work if I once want to refactor the post attributes). 
And if I do that, I'd have to loop over all results, search if the key contains my alias and then create 2 distinct arrays (one post and one user) with which I can instantiate both objects. Not sure if this is exactly a "clean" approach, but I don't see how I could do it otherwise. How would you do that? 
This is the code I have so far, but I would have to be in a smart generic hydrate function right?
```php
$query = $this->queryFactory->newQuery()->from('post');
$query->select(
    [
        'post_message' => 'post.message',
        'post_updated_at' => 'post.updated_at',
        'post_created_at' => 'post.created_at',
        'user_name' => 'user.name',
        'user_email' => 'user.email',
        'user_role' => 'user.role',
        'user_status' => 'user.status',
    ]
)->join(['table' => 'user', 'conditions' => 'post.user_id = user.id'])->andWhere(
    ['post.deleted_at IS' => null]
);
$resultRows = $query->execute()->fetchAll('assoc');
// Convert to list of Post objects with associated User
$postsWithUsers = [];
foreach ($resultRows as $rowValues) {
    $postRow = [];
    $userRow = [];
    foreach ($rowValues as $column => $value) {
        // Check if column name (alias) starts with user_ and if so, remove it
        if (str_starts_with($column, 'post_')) {
            $postRow[str_replace('post_', '', $column)] = $value;
        }
        if (str_starts_with($column, 'user_')) {
            $userRow[str_replace('user_', '', $column)] = $value;
        }
    }
    $post = new Post($postRow);
    $post->user = new User($userRow);
    $postsWithUsers[] = $post;
}
```

The second option and the easiest programmatically is to make 2 queries. I once select the posts I want and then for each post I make a new query to find the user info. That is a lot more db queries and therefore a lot less efficient, right?

**Comment by odan** [comment]
I cannot give a generic and universal answer here, because the answer depends on the context.

This is **not** a Active Record pattern. Don't reuse the same (generic) object for all different use cases.  Create use case specific objects instead and fill that DTO with data. Your Repository could also just return a simple array (the result set) and the mapping happens within the service (when needed). 

The query should only select fields that you really need. You could also invoke other Repository methods when needed.

When you write a query, and you select fields from different tables it doesn't matter (for the DTO and the consumer) where these fields are coming from. So here are just two examples:

Please note: In reality, you would just return a list of posts from a specific user. So I changed the example a little.

```php
<?php

final class UserPost
{
    public string $postMessage;
    public DateTimeImmutable $postUpdatedAt;
    public DateTimeImmutable $postCreatedAt;
    public string $userName;
    public string $userEmail;
    public string $userRole;
    public int $userStatus;

    public function __construct(array $data = [])
    {
        // Init object
       $this->postMessage = $data['post_message'] ?? '';
        // and so on...
    }
}

final class ExampleRepository
{
    // the constructor
    // ...

    /**
     * Find posts by user id.
     *
     * @param int $userId The user id
     *
     * @return UserPost[] The list
     */
    public function findPostsByUserId(int $userId): array
    {
        $query = $this->queryFactory->newQuery()->from('post');

        $query->select(
            [
                'post_message' => 'post.message',
                'post_updated_at' => 'post.updated_at',
                'post_created_at' => 'post.created_at',
                'user_name' => 'user.name',
                'user_email' => 'user.email',
                'user_role' => 'user.role',
                'user_status' => 'user.status',
            ]
        );

        $query->innerJoin('user', 'user.id = post.user_id');

        $query->andWhere(
            [
                'user.id' => $userId,
                'post.deleted_at IS' => null,
            ]
        );

        $rows = $query->execute()->fetchAll('assoc');

        // convert to list of objects
        $result = [];
        foreach ($rows as $row) {
            $result[] = new UserPost($row);
        }

        return $result;
    }
}
```


The other option would be to map the values from the result set manually. Example:

```php
$result = [];
foreach ($rows as $row) {
    $userPost = new UserPost();
    $userPost->postMessage = (string)$row['post_message'];
     // ... and so on...

    $result[] = $userPost;
}
```

You could also use a hydrator, or you just return the result set as array and handle it within the service. It depends.

**Comment by odan** [comment]
PS: I would recommend this video: https://www.youtube.com/watch?v=r0-GC3Y_OME because it explains the principle in other words then I can do.

**Comment by samuelgfeller** [comment]
Great example, thank you. So creating a very specific DTO. That goes directly in the way of a "Use case" based approach which totally makes sense in our case. And probably I would almost only need this object for posts as most of the use cases where I retrieve a post I need some user info too. 

For me though I feel like this is slightly a too big shift yet. There's a good chance that I will come back to this later but for now I prefer to map them "manually" with a hydrator which gives me a kind of the feeling of flexibility still. Or handling it within the service, but I find it slick if the repository can return objects. 

I made the following and would love some feedback (also about naming / comments / logic, everything):
```php
// AllPostWithUserFinderRepository.php
public function findAllPostsWithUsers(): array
{
    $query = $this->queryFactory->newQuery()->from('post');
    $query->select(
        [
            'post_message' => 'post.message',
            'post_updated_at' => 'post.updated_at',
            'post_created_at' => 'post.created_at',
            'user_name' => 'user.name',
            'user_email' => 'user.email',
            'user_role' => 'user.role',
            'user_status' => 'user.status',
        ]
    )->join(['table' => 'user', 'conditions' => 'post.user_id = user.id'])->andWhere(
        ['post.deleted_at IS' => null]
    );
    $resultRows = $query->execute()->fetchAll('assoc');
    // Convert to list of Post objects with associated User
    return $this->hydrator->hydrateAggregates($resultRows, [Post::class, 'post_'], [[User::class, 'user_', 'user']]);
}
```
Hydrate function:
```php
/**
 * Hydrate a collection of objects that are aggregates, meaning they contain loaded associate objects
 *
 * @template T
 *
 * @param array<array> $aggregateRows Rows with values from different tables
 * @param array<class-string<T>|string> $aggregateClass main class that will have instances of given
 * associations (first array value) and alias used in query (second)
 * @param array<array<class-string|string>> $associations classes (first), beginning of alias used in query (second)
 * and its attribute name in the main class (third)
 *
 * @return T[] The list of object
 */
public function hydrateAggregates(array $aggregateRows, array $aggregateClass, array $associations) {
    $aggregateObjects = [];
    // Alias name is second value of array
    $mainAlias = $aggregateClass[1];
    foreach ($aggregateRows as $rowValues) {
        /** @var array<array<mixed>> $moduleRows reconstruction of result rows but separated by table */
        $moduleRows = [];
        foreach ($rowValues as $column => $value) {
            // Check if column name (alias) starts with given alias (e.g. "post_")
            if (str_starts_with($column, $mainAlias)) {
                // Add value to $moduleRows sub array for the reconstruction of clean rows bound to table
                $moduleRows[$mainAlias][str_replace($mainAlias, '', $column)] = $value;
            }
            // Put all aggregate values in distinct array
            foreach ($associations as $association) {
                $associateAlias = $association[1];
                // Check if column name (alias) starts with given alias (e.g. "post_")
                if (str_starts_with($column, $associateAlias)) {
                    // Add value to $moduleRows sub array for the reconstruction of clean rows bound to table
                    $moduleRows[$associateAlias][str_replace($associateAlias, '', $column)] = $value;
                }
            }
        }
        // Class name is the first value of the $aggregateClass array
        /** @var T $aggregateObj */
        $aggregateObj = new $aggregateClass[0]($moduleRows[$mainAlias] ?? []);
        // Add associations to main object (aggregate)
        foreach ($associations as $association) {
            // Attribute name of association in main object is third value
            $attr = $association[2]; // Array to string exception if not done via variable
            // Associate class name is first value of $association array and alias is the second
            $aggregateObj->$attr = new $association[0]($moduleRows[$association[1]] ?? []);
            // Cleartext example: $post->user = new User(['first_name' => 'Bill', 'second_name' => 'Gates']);
        }
        $aggregateObjects[] = $aggregateObj;
    }
    return $aggregateObjects;
}
```

**Comment by odan** [comment]
Oh no, I think this kind of complexity is not good and will not work. Don't reinvent the ORM again. Keep it simple.

**Comment by samuelgfeller** [comment]
I wasn't even realizing that I was doing exactly that... I wanted to avoid code duplication in the repositories that retrieve Posts at all cost, but I guess the cost of added complexity is too high. 
I have a hard time now deciding if I should make the PostWithUserData DTO or map them manually. I just don't have enough experience with larger projects and on this small scale with such few columns, associations and classes (only 1) it really doesn't matter.
Probably what I'll end up doing is a mix of all. Like you said, it depends on the situation but to know what's best the situation has to be more complex, right? 

I assume that all larger projects where you implement that use case based approach with a lot of production example are closed source. Or is there any I could browse through and see what's done depending on a situation?
Or maybe you could just tell me which you use the most in production. But in any case I will end up finding out anyway. 

**Edit**: Okay after sleeping on it, re-reading your answer carefully and watching the video I realized that I got everything wrong. 
I don't know what happened to me then, probably I was exhausted and or not open for such a drastic change in my way of thinking / programming. Of course, I should make the use case DTO and with "map manually" you didn't mean map generic objects with needed values but map the `UserPost` as the code examples show.

**Comment by samuelgfeller** [comment]
How do you decide how the repository is called and are you splitting them like one repository per use case or do you still make grouped repositories with multiple functions in them?

How would you call it, `PostRepository`, `PostFinderRepository`, `UserPostRepository` or `UserPostFinderRepository` or else?
