### ISSUE TITLE
Can you please put an example PATCH?

### ISSUE THREAD

**Issue by androiduser2209** [odan/slim4-tutorial#38]
Hi @odan , how are you? I bought your ebook, I thought it was very good for the development of my project. However, I searched it and didn't find an example of PATCH.

However, I need an example of PATCH, as I think it is costly to send the entire object every time by PUT to be updated. I'm able to create a PATCH route by myself, but I know that starting from you it will be more correct to be followed by example throughout my project, which has 140 tables.

I tried converting PUT to PATCH, but as I'm a beginning programmer, I wasn't completely sure I'm doing it right. I think a lot about the maintainability of the code, something its SLIM 4 skeletal details sensationally.

PS: If you say it's better to PUT the entire object (for validation reasons, etc), I'll use PUT throughout my project.

Thank you so much for everything.

**Comment by odan** [comment]
Hi @androiduser2209 

As I mentioned in the eBook every endpoint should be designed for each specific **use case**.

When you design an API you don't need CRUD endpoints with GET/POST/PUT/PATCH/DELETE for each database table. 
HTTP is not a persistence layer for your tables. An API should hide all these technical details (like tables etc).

I think there is no special `PATCH` example required when you design your API for each specific **use case**, then it should be more clear what this specific endpoint should exactly do.
