### ISSUE TITLE
Slim 4 NGINX web server.

### ISSUE THREAD

**Issue by ridwan-aswan** [odan/slim4-tutorial#4]
can you help me, I try to implement it as you have, and it works fine on apache, but when I move it to NGINX index.php in the public folder it can't be called, I've followed this method http: //www.slimframework.com/docs/v4/start/web-servers.html # nginx-configuration, but it still fails. please help. thank you
<img width="389" alt="Screen Shot 2020-07-24 at 21 33 09" src="https://user-images.githubusercontent.com/56959334/88406824-6698d980-cdfb-11ea-91af-612f8ac343d7.png">

<img width="625" alt="Screen Shot 2020-07-24 at 22 14 14" src="https://user-images.githubusercontent.com/56959334/88406623-2174a780-cdfb-11ea-868a-9d974397695c.png">

**Comment by odan** [comment]
It looks like the `root` path is missing. The example from http://www.slimframework.com/docs/v4/start/web-servers.html#nginx-configuration should work. I have tested it.

```
server {
    listen 80;
    server_name example.com;
    index index.php;
    error_log /path/to/example.error.log;
    access_log /path/to/example.access.log;
    root /path/to/public;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_index index.php;
        fastcgi_pass 127.0.0.1:9123;
    }
}

**Comment by ridwan-aswan** [comment]
Thank you, I sent a private message to your Twitter.
