### ISSUE TITLE
How to read JWT Token content in my Action?

### ISSUE THREAD

**Issue by esallum-iluminare** [odan/slim4-tutorial#40]
Hi @odan , how are you? Following the ISSUE of this topic I created (https://github.com/odan/slim4-skeleton/issues/74), I decided to open a new one here at Slim4-Tutorial.

As I said in this topic above, my application will have several types of users (increased to 9 in total). Everyone will receive the JWT Token if the login is valid, and inside the JWT Token will be the login and user type info.

I need to check in all Actions of my application if the type of user that is stored in the token can access a certain route. My doubts are: 

1 - What is the best way to read and validate the information that is inside the Token JWT in my Actions?

2 - All my routes will be registered in the BD. Since this check will be common to all routes, can I get my actions to invoke a common Service?

3 - Is there any dynamic way to read which route, defined in the routes.php file, invoked the Action?

Thanks in advance!

**Comment by esallum-iluminare** [comment]
Solved by using `$request->getHeader("Authorization");`

**Comment by odan** [comment]
1) In my [Slim 4 eBook](https://ko-fi.com/s/5f182b4b22) I have written a lot about JSON Web Token (JWT) authentication. 
2) What do you mean with "BD"? You can validate that within a Middleware that uses a (optional) Service for complexer logic.
3) I'm not sure what this should be good for. Do you have more context?

**Comment by esallum-iluminare** [comment]
Hi @odan. Thanks for the help.

2 - Sorry about the wrong translate. BD = Base de Dados (portuguese) -> DB = Database (english). For this question, I resolved this by creating a Service (that can be invoked by any other Service, according by Slim 4 eBook) that valuates the User Authorization through the _user_uuid_ parameter that I read from the JWT token (in the Actions of my project) using `$request->getHeader("Authorization");`  

3 - In the question 3, what I mean is this: Suppose in my routes.php file I invoke the Action titled UserRead:
Route: `$app->get('/users/{uuid_user}', \App\Action\User\UserReadAction::class);`

Is there any way in the Action code to get the URL of the route in question? For example:

```

UserReadAction{
[...]
echo $route;
}
```

Desired output from variable $route:

  _https://myproject.com/api/users/649ca95c-a218-4892-b0ed-b6abbfa84858_

or:

_users/649ca95c-a218-4892-b0ed-b6abbfa84858._ 

Thanks in advanced!

**Comment by odan** [comment]
You can give each route [a name](https://www.slimframework.com/docs/v4/objects/routing.html#route-names) with `->setName('hello');`.

You can generate a URL for a named route with the application RouteParser’s urlFor() method.

```php
use Slim\Routing\RouteContext;
// ...

$routeParser = RouteContext::fromRequest($request)->getRouteParser();
```
...or like this:

```php
$routeParser = $app->getRouteCollector()->getRouteParser();
```

Then it's possible to use the `urlFor`, `fullUrlFor` or `relativeUrlFor` method to build a URL.

```php
$url = $routeParser->urlFor('hello');
```
Read more: [Route names](https://www.slimframework.com/docs/v4/objects/routing.html#route-names)

**Comment by esallum-iluminare** [comment]
Thanks @odan !
