### ISSUE TITLE
Can't compile assets

### ISSUE THREAD

**Issue by mconrejas** [odan/slim4-tutorial#41]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build:dev' ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prebuild:dev', 'build:dev', 'postbuild:dev' ]
5 info lifecycle ecolawn@1.0.0~prebuild:dev: ecolawn@1.0.0
6 info lifecycle ecolawn@1.0.0~build:dev: ecolawn@1.0.0
7 verbose lifecycle ecolawn@1.0.0~build:dev: unsafe-perm in lifecycle true
8 verbose lifecycle ecolawn@1.0.0~build:dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/customer_ecolawn_nz/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle ecolawn@1.0.0~build:dev: CWD: /var/www/html/customer_ecolawn_nz
10 silly lifecycle ecolawn@1.0.0~build:dev: Args: [ '-c', 'npx webpack --mode=development' ]
11 silly lifecycle ecolawn@1.0.0~build:dev: Returned: code: 1  signal: null
12 info lifecycle ecolawn@1.0.0~build:dev: Failed to exec build:dev script
13 verbose stack Error: ecolawn@1.0.0 build:dev: `npx webpack --mode=development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid ecolawn@1.0.0
15 verbose cwd /var/www/html/customer_ecolawn_nz
16 verbose Linux 5.11.0-34-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dev"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error ecolawn@1.0.0 build:dev: `npx webpack --mode=development`
22 error Exit status 1
23 error Failed at the ecolawn@1.0.0 build:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Keep getting this errors:
error code ELIFECYCLE
error errno 1
error ecolawn@1.0.0 build:dev: `npx webpack --mode=development`
error Exit status 1
error Failed at the ecolawn@1.0.0 build:dev script.

**Comment by odan** [comment]
Hi! This error-dump is not very helpful. Add more details.
