### ISSUE TITLE
404 on loading assets

### ISSUE THREAD

**Issue by shorif2000** [odan/slim4-tutorial#42]
**Describe the bug**
I have followed this with the following structure

<img width="254" alt="Screenshot 2021-12-09 at 23 27 25" src="https://user-images.githubusercontent.com/6359089/145491649-0d54fc50-af88-4a7a-9cd2-4206abbec7ee.png">

When I load the and image i keep getting 404 error
```

"details": {
        "message": "Not found."
    },
    "message": "",
    "class": "HttpNotFoundException",
    "status": "error",
    "code": 404,
    "fileLoc": "app/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php",
    "lineN": 91

```

I had to do this https://grahamlikesto.codes/slim-php-how-to-serve-static-files-with-slim-php/ to get the assets loading

**Comment by odan** [comment]
The shown workaround may work, but is not optimal, because it requires to invoke PHP and Slim just to fetch some static files.
