### ISSUE TITLE
Redirect to GET request after non-GET request

### ISSUE THREAD

**Issue by samuelgfeller** [odan/slim4-tutorial#44]
Hey Daniel 
I've got a small issue. I have this in `UserAuthenticationMiddleware.php` 
```php
public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface {
    if ($this->session->get('user_id')) {
        return $handler->handle($request);
    }
    $response = $this->responder->createResponse();
    $this->session->getFlash()->add('info', 'Please login to access this page.');
    return $this->responder->redirectToRouteName(
        $response, 'login-page', [], ['redirect' => $request->getUri()->getPath()]
    );
}
```
Which redirects the user to the login page if the area is protected, and he's not logged in. 
Now, there is the case where the user submits a form (POST) or makes an edit which creates a PUT-request without being logged in (session expired or logged out on another tab).

With my present code, the redirect request to the login page is with the same method as the original request which makes sense in most cases but here I want to specifically make a GET-redirection because I have no PUT route for the login page (405 Method Not Allowed). 

I've tried to add `$request = $request->withMethod('GET');` before making the redirect which, as expected, did not work.  

Where does this PUT method of the request influence the redirected response, and how do I change it into GET? 

Cheers

**Comment by odan** [comment]
Hi Samuel. This depends on how your client works. Do you use Ajax for the requests or a "classic" POST form submit?

If you send a normal POST/PUT request then you may try to use the Post/Redirect/Get (PRG) pattern.

* https://en.wikipedia.org/wiki/Post/Redirect/Get
* https://www.theserverside.com/news/1365146/Redirect-After-Post

**Comment by samuelgfeller** [comment]
Thanks for the links, I'll look into it. I make an Ajax PUT request and also intend to do Ajax DELETE requests. If the user is not logged in and tries to make those PUT, DELETE or POST requests, I want him to be redirected to the GET login page. For now, I don't care about the input submitted, if he's not logged in it should not affect the database at all, just a GET redirect to the login page. 

A quick and dirty solution would be to make PUT, DELETE and POST routes for the `/login` URL, but I thought for sure this was an awful approach, so I didn't even mention it. But should I do that after all?

Edit: The PRG pattern makes a lot of sense and seems to be an obvious, smart thing to do. My question is more technically, _how_ to redirect to a GET request after a non-GET request in the most simple / efficient way with slim. (I'd probably have the same question if I wanted to implement the PRG pattern). 

This is my `UserSubmitUpdateAction.php`
```php
public function __invoke(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface {
    if (($loggedInUserId = $this->session->get('user_id')) !== null) {
        // ... code that makes the change ...
        // return success response
    }
    // not logged in
    return $response;
}
```
Then it's picked up by the `UserAuthenticationMiddleware.php` which makes the PUT redirect, right? At which place and how do I tell it to force a GET redirect even if an incoming request is PUT? I thought that would maybe be in the `Responder.php` but I didn't find a way there.

**Comment by odan** [comment]
Technically, it's not possible a change a request to something else, e.g. from POST to GET. You can only send a redirect with the new url. The client (e.g. browser) then "follows" this new url by requesting the new url (in a new request). But when you make an ajax call the user still stays on the same "page" because the Ajax request does not affect the actual shown html page. This means you have to redirect the user via JavaScript to the new page if the Ajax response returns an HTTP redirect. Did I understand your question right?

**Comment by samuelgfeller** [comment]
Oh alright. Yes that makes perfect sense. 

The response to the request in itself returned PUT 302 Found which makes a lot of sense to me.
![request](https://i.imgur.com/G6ZdvCF.png)

I guess I was confused because then another request pops up in the Network tab which points to the login page. 
![login request](https://i.imgur.com/fASYL5k.png)
And this one is also PUT. I thought the server could "forcefully" send over a GET redirection, which the browser then recognizes and loads. But obviously the assumption that it could work like this was fundamentally wrong, I have to adapt the client, not server. 

I'll try it out and give an update.

**Comment by samuelgfeller** [comment]
Struggling a liiiitle to implement a neat solution. 
Is [that](https://stackoverflow.com/a/26214803/9013718) true?
> You can not redirect on ajax call, because, it expects some return value from the invoked page. And if that page itself redirects, it has no way to tell calling function to redirect, as it simply expects some return value in success callback.

[All](https://stackoverflow.com/questions/199099/how-to-manage-a-redirect-request-after-a-jquery-ajax-call) [the](https://stackoverflow.com/questions/16871289/how-to-redirect-response-from-ajax-request/16871363) [solutions](https://stackoverflow.com/questions/43971141/res-redirect-from-an-ajax-call) I've [found](https://stackoverflow.com/questions/3513971/page-redirect-with-successful-ajax-request) were just adding a parameter in the body. Not very beautiful. I want an `AuthMiddleware` that sends a location header for all the restricted GET areas. 

This is what I have tried but the relevant `if` statement is never reached. Only on the 405 response of the redirect :
```js
    let xHttp = new XMLHttpRequest();
    xHttp.onreadystatechange = function () {
        if (xHttp.readyState === XMLHttpRequest.DONE) {
            if (xHttp.getResponseHeader('Content-type') === 'application/json') {
                if (xHttp.status !== 200) {
                    handleFail(xHttp);
                }
                if (xHttp.status === 422) {
                    // Validation error, mark input element with a red line
                    inputElement.className += ' wrong-cred-input';
                } else {
                    createFlashMessage('success', 'Successfully changed ' + inputName);
                }
            }
            // If status found is returned, a GET redirect has to be done
            if (xHttp.status === 302){
              let location = xHttp.getResponseHeader('Location');
              if (location !== null) {
                  // Redirect to given location
                  window.location.href = location;
              }
          } 
        }
       /*  I tried to puting it here too 
        if (xHttp.status === 302){
            let location = xHttp.getResponseHeader('Location');
            if (location !== null) {
                // Redirect to given location
                window.location.href = location;
            }
        } */
    };

// Opening and sending the request 
```
He observed [the same thing](https://stackoverflow.com/a/10717647/9013718).


Seriously, what do you think about an exceptional route to `LoginViewAction` in all the HTTP methods? I've used POST for when the form is submitted, but I could use a different URL. I'd find that better than the solutions suggested above if I can't make it redirect to the response Location header.    


### Edit
Okay this works:
```js
if (xHttp.status === 405){
        // Redirect to response url
        window.location.href = xHttp.responseURL;
    }
}
```
Feel free to criticize bad practices you see or bad reasoning. I'm keen to learn.

**Comment by odan** [comment]
For the Ajax endpoints, I would not return a "redirect" response if the user is not logged in. Instead I would just throw a 
`HttpUnauthorizedException` ~~`HttpMethodNotAllowedException`~~ so that the Ajax client is able to handle this HTTP code within an error handler function on the client side. Then you could check the HTTP status code (401) and redirect the Browser to the login page with `window.location.href = '/login';`

For the HTML pages, you could also throw a `HttpUnauthorizedException` ~~`HttpMethodNotAllowedException`~~, but then your middleware would transform this into a normal redirect response. The other option would be to render an HTML page with the error message (You are not logged in, you will be redirected to the login page in 5 seconds.) that contains a JavaScript timer that redirects the User after 5 seconds to the login page.

To detect if its an Ajax request or not, your HttpUnauthorizedExceptionMiddleware could check the request `HTTP_X_REQUESTED_WITH` request header for a value like `xmlhttprequest`. An Ajax clients like Axios has to be configured to send this request header.

**Comment by samuelgfeller** [comment]
> Instead I would just throw a HttpMethodNotAllowedException so that the Ajax client is able to handle this HTTP code within an error handler function on the client side. Then you could check the HTTP status code (405) and redirect the Browser to the login page with

Isn't that exactly what I did in my edit? The server returns a response to the login request as 405 Method Not Allowed and in the Ajax from the client side it picks that error code up and redirects the browser to the login page:
```js
if (xHttp.status === 405){
        // Redirect to response url being the /login that failed with PUT
        window.location.href = xHttp.responseURL;
    }
}
```

**Comment by odan** [comment]
Ah yes, in your edit.  Maybe I just was confused because of this: `xHttp.responseURL`

**Comment by samuelgfeller** [comment]
I was thinking. Somehow the 405 Method Not Allowed solution doesn't satisfy me fully. I feel like I'm using a specific error code for something very different from its initial purpose.   

And I have a new related issue now. It's about the redirection back to the page after a successful login. 

If a user clicks on the delete button of a post, but he was logged out on a different tab before that, the Ajax call to delete the post will be caught by the `AuthMiddleware` which makes the redirect to the login page. 

But here is the thing, I want it to make the redirect to the login page and as query param, have the url that it should redirect AFTER the login. Typically, where the user was before that.  I always hate it when I'm doing something, the website asks for login, and then I'm on the homepage or whatever. I want to be where I was interrupted. 

I had this line in my `AuthMiddleware`: 
```php
return $this->responder->redirectToRouteName(
    // Adding 'redirect' query param of failed url for the login action to redirect after a success.
    $response, 'login-page', [], ['redirect' => $request->getUri()->getPath()]
);
```

You probably see it coming, this works beautifully for normal pages (non-Ajax, rendered by the server) that are protected by the `AuthMiddleware` such as `/own-posts` or `/profile` but for all others this solution is not a solution to begin with. I don't want the user to be redirected to GET `/posts/1` (which is the post details as JSON) when he is trying to delete this post. 

So I want to find a way to custom decide where the login page should redirect after success. I have two ideas:

### Not use AuthMiddleware to protect Ajax routes
Check in each Ajax action if the user is logged in (which I'm doing anyway) and if not, make the redirect to the login page with the correct query param for the next redirection. 

Curious about what you think about this. I kind of like it for its simplicity, and it does make sense, but it brings inconsistency in the `routes.php` file and a new "rule" or concept that I have to take care of or one would have to learn. I would rather add `AuthMiddleware` to each protected route and find a better solution that works consistently and in the best case also allows me to not use 405 for the login redirection. 

### Using a custom HTTP header
While doing the xHttp request from the client, I could add a header like `Redirect-to-if-unauthorized` containing the route name to each request. Like:
```js
    let xHttp = new XMLHttpRequest();
    // Add custom redirect header with route name to Ajax call
    xHttp.setRequestHeader("Redirect-to-if-unauthorized", "post-list-own-page");

    xHttp.onreadystatechange = function () {
        if (xHttp.readyState === XMLHttpRequest.DONE) {
            // Not logged in, redirect to login url
            if (xHttp.status === 401) {
                let loginUrl = JSON.parse(xHttp.responseText).loginUrl;
                window.location.href = loginUrl;
            }
    // ...
```
`AuthMiddleware`
```php
        // ...
        $queryParams = [];
        // If header Redirect-to-if-unauthorized is set, add it to the query params of the login route
        if (($routeName = $request->getHeaderLine('Redirect-to-if-unauthorized')) !== '') {
            // Redirect to after login
            $queryParams['redirect'] = $this->responder->urlFor($routeName);
        }

        // If it's a JSON request return 401 with the login url and its possible query params
        if ($request->getHeaderLine('Content-Type') === 'application/json') {
            return $this->responder->respondWithJson(
                $response,
                ['loginUrl' => $this->responder->urlFor('login-page', [], $queryParams)],
                401
            );
        }

        // If no redirect header is set, and it's not a JSON request, redirect to same url as the request after login
        return $this->responder->redirectToRouteName($response, 'login-page', [], $queryParams);
    }
```
With that, I would not only have a dedicated "thing" for the redirection and don't have to use an exception (405) that is made for something else, but also have a consistent logic and an `AuthMiddleware` that could handle normal routes and Ajax routes with the `Redirect-to-if-unauthorized` header. 
Drawbacks would be that I have to write the route name in the client js file which I don't like because it's mixing server and client things and adding a dependency to update the route name there as well if I change it.
Also, each request has more data to transfer in 99% cases for nothing. 
And finally, I don't know if its good practice to use HTTP methods for this kind of stuff. That's why I'm asking.

What is your opinion on these approaches, and how would you do it? 


Edit: I edited the second suggestion to use 401 instead of 405.

**Comment by odan** [comment]
Yes, I just saw that I wrote 405, but I mean 401 (HttpUnauthorizedException).

Personally, I would not make it so complicated. I would just catch all 401er HTTP codes and redirect the client to a fix url path of the login page.

**Comment by samuelgfeller** [comment]
Ah okay, indeed makes more sense.

Being redirected back to the place where one was before being asked to log in is a must in my application. 

I don't just want to just redirect the login URL without redirect back parameter.

And it's a lot about learning as well, I'm trying to do the most I can _once_ as an example, so I don't have to learn it later. If I have a good solution to this issue, that will surely inspire me in the future when I want to do a similar thing. 

That's why I'm so curious, just about your opinion on both solutions suggested. You have a lot more experience and knowledge, so you probably know better if chances are that I am bothered in the future because they're not proper. 

Does something speak against using the custom request header, apart from the added complexity, in your opinion?

**Comment by samuelgfeller** [comment]
I can't believe I haven't thought of this earlier. The redirect back to the current page query param when a non-authenticated Ajax request is made can easily be done with JavaScript. No need for a custom header and intervention from the server. 

The goal is always to redirect back to the current page the user has open in the browser, and this can be retrieved with JS after the request failed with status `401` and then added to the login url (coming from the server or hardcoded): 
`loginUrl + '?redirect=' + encodeURIComponent(window.location.href);`

```js
return fetch(route, {method: 'GET', headers: {"Content-type": "application/json"}})
    .then(response => {
        if (!response.ok) {
            if (response.status === 401) {
                window.location.href =  basePath + '/login?redirect=' + encodeURIComponent(window.location.href);
            }
            throw response;
        }
        return response.json();
    });
```
