### ISSUE TITLE
Re: Tutorial for slim4-skeleton

### ISSUE THREAD

**Issue by sivakrith** [odan/slim4-tutorial#46]
Hello Odan,
Is there any tutorial that explains steps by step installation, running of the slim4-skeleton project that's been hosted here?  The tutorial available is good but a basic one that doesn't correlate to the one hosted here.  
Would like to have one that explains the same way as the basic one.   That tutorial could be either paid or free.   
Would like to hear from you.
Thanks.

**Comment by odan** [comment]
Hi @sivakrith 

Note that there are different repositories on github.

This Github repository (https://github.com/odan/slim4-tutorial) refers to this [Slim 4 - Tutorial](https://odan.github.io/2019/11/05/slim4-tutorial.html) on my blog.

Then there is also this Github repository (https://github.com/odan/slim4-skeleton), a complete Slim 4 Skeleton, with much more features. This project is documented here: https://odan.github.io/slim4-skeleton/
