### ISSUE TITLE
[Question] How Made IoC or inverse dependency use PHP-DI

### ISSUE THREAD

**Issue by NicolasPereira** [odan/slim4-tutorial#47]
Hi Odan, how are you?
First I would like to thank you for your Slim 4 tutorial! I'm a PHP student and I work with Laravel but I decided to study Slim to cover my knowledge!

I implemented Doctrine in the project according to the Slim documentation, adding in this case the `EntityManager` configuration in our `container.php` file, as shown in your tutorial, and it worked perfectly! 

I would like to know if with PHP-DI it is possible to create Dependency Inversion! I would like to do something like:

 `EntityManager::class => EntityManagerFactory::class,`

Below is my `EntityManagerFactory`

```php
class EntityManagerFactory
{
    public function __invoke(ContainerInterface $container): EntityManagerInterface
    {
        $settings = $container->get('settings')['db'];
        $cache = $settings['dev_mode'] ?
            DoctrineProvider::wrap(new ArrayAdapter()) :
            DoctrineProvider::wrap(new FilesystemAdapter(directory: $settings['cache_dir']));

        $config = Setup::createAttributeMetadataConfiguration(
            $settings['metadata_dirs'],
            $settings['dev_mode'],
            null,
            $cache
        );

        return EntityManager::create($settings['connection'], $config);
    }
}
```
This is my `bootstrap.php` like your tutorial: 
```php
require_once __DIR__ . '/../vendor/autoload.php';

$containerBuilder = new ContainerBuilder();

// Set up settings
$containerBuilder->addDefinitions(__DIR__ . '/container.php');
// Build PHP-DI Container instance
$container = $containerBuilder->build();
// Create App instance
$app = $container->get(App::class);
// Register routes
(require __DIR__ . '/routes.php')($app);

// Register middleware
(require __DIR__ . '/middleware.php')($app);

return $app;
```

Bellow is my `container.php`

```php
return [
    'settings' => function () {
        return require __DIR__ . '/settings.php';
    },

    App::class => function (ContainerInterface $container) {
        AppFactory::setContainer($container);

        return AppFactory::create();
    },

    ResponseFactoryInterface::class => function (ContainerInterface $container) {
        return $container->get(Psr17Factory::class);
    },

    ErrorMiddleware::class => function (ContainerInterface $container) {
        $app = $container->get(App::class);
        $settings = $container->get('settings')['error'];

        return new ErrorMiddleware(
            $app->getCallableResolver(),
            $app->getResponseFactory(),
            (bool)$settings['display_error_details'],
            (bool)$settings['log_errors'],
            (bool)$settings['log_error_details']
        );
    },

    BasePathMiddleware::class => function (ContainerInterface $container) {
        return new BasePathMiddleware($container->get(App::class));
    },
    EntityManager::class => EntityManagerFactory::class
];
```

Finaly, this is my `cli-config.php`

```php
<?php
// cli-config.php
use DI\Container;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;

/** @var Container $container */
$app = require_once __DIR__ . '/config/bootstrap.php';
$container = $app->getContainer();
return ConsoleRunner::createHelperSet($container->get(EntityManager::class));
```

When trying to run in the terminal vendor/bin/doctrine I get this error:

```shell
Fatal error: Uncaught TypeError: Doctrine\ORM\Tools\Console\ConsoleRunner::createHelperSet(): Argument #1 ($entityManager) must be of type Doctrine\ORM\EntityManagerInterface, string given, called in /var/www/slim_app/cli-config.php on line 10 and defined in /var/www/slim_app/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php:31
Stack trace:
#0 /var/www/slim_app/cli-config.php(10): Doctrine\ORM\Tools\Console\ConsoleRunner::createHelperSet('App\\Infrastruct...')
#1 /var/www/slim_app/vendor/doctrine/orm/bin/doctrine.php(51): require('/var/www/slim_a...')
#2 /var/www/slim_app/vendor/doctrine/orm/bin/doctrine(4): include('/var/www/slim_a...')
#3 /var/www/slim_app/vendor/bin/doctrine(120): include('/var/www/slim_a...')
#4 {main}
```

If you see the error on line `#0`  it is passing the EntityManagerFactory file and not my already invoked class.

Can you help me or even point me to articles that address IoC or Dependency Inversion with PHP-DI?

Thank you very much in advance for your support.

**Comment by odan** [comment]
Hi @NicolasPereira 

Instead of this: 

>  EntityManager::class => EntityManagerFactory::class

... you can try this to use the factory:

*This example with the closure is not best practice*

```php
EntityManager::class => function (ContainerInterface $container) {
    $factory = $container->get(EntityManagerFactory::class); 
    return $factory($factory);
},
```

Note that you could also use a normal method for the factory, e.g. `createInstance` or `createEntityManager`. I would refactor it a little bite like this to make it more DI container friendly.

```php
// ...

final class EntityManagerFactory
{
    private array $settings;

    public function __construct(array $settings) 
    {
        $this->settings = $settings;
    }

    public function createEntityManager(): EntityManagerInterface
    {
        $cache = $this->settings['dev_mode'] ?
            DoctrineProvider::wrap(new ArrayAdapter()) :
            DoctrineProvider::wrap(new FilesystemAdapter(directory: $settings['cache_dir']));

        $config = Setup::createAttributeMetadataConfiguration(
            $this->settings['metadata_dirs'],
            $this->settings['dev_mode'],
            null,
            $cache
        );

        return EntityManager::create($this->settings['connection'], $config);
    }
}
```

In container.php:

```php
EntityManagerFactory::class => function (ContainerInterface $container) {
    $settings = $container->get('settings')['db'];
    
    return new EntityManagerFactory($settings);
},
EntityManager::class => function (ContainerInterface $container) {
    return $container->get(EntityManagerFactory::class)->createEntityManager(); 
},
```

Edit: The simplest solution would be to implement the factory directly in the DI container definition. Then you don't need the EntityManagerFactory class.

**Comment by NicolasPereira** [comment]
Hi @odan! I read the PHP-DI documentation and found Di/Factory, implemented the implementation in my code and it looks like this.

My `EntityManagerFactory`  

```php
class EntityManagerFactory
{
    public static function create( ContainerInterface $container): EntityManagerInterface
    {
        $settings = $container->get('settings')['db'];
        $cache = $settings['dev_mode'] ?
            DoctrineProvider::wrap(new ArrayAdapter()) :
            DoctrineProvider::wrap(new FilesystemAdapter(directory: $settings['cache_dir']));

        $config = Setup::createAttributeMetadataConfiguration(
            $settings['metadata_dirs'],
            $settings['dev_mode'],
            null,
            $cache
        );

        return EntityManager::create($settings['connection'], $config);
    }
}
```
Now, i create  `dependencies.php`

```php
    EntityManager::class => DI\factory(function(ContainerInterface $container): EntityManagerInterface {
        return EntityManagerFactory::create($container);
```

I also performed the segregation of `container.php` and `dependencies.php`

The `container.php ` file is now just with the classes from your tutorial while the` dependencies.php` will leave the dependencies and interfaces inversions of my project.

Does it make sense to have this segregation of files?

My `bootstrap.php` file looks like this!

```php
<?php

use DI\ContainerBuilder;
use Slim\App;


require_once __DIR__ . '/../vendor/autoload.php';

$containerBuilder = new ContainerBuilder();

// Set up settings
$containerBuilder->addDefinitions(__DIR__ . '/dependencies.php');
$containerBuilder->addDefinitions(__DIR__ . '/container.php');
// Build PHP-DI Container instance
$container = $containerBuilder->build();
// Create App instance
$app = $container->get(App::class);
// Register routes
(require __DIR__ . '/routes.php')($app);

// Register middleware
(require __DIR__ . '/middleware.php')($app);

return $app;
```

The way I presented above worked, if you have any tips on how to improve, feel free to tell me!

Thanks for your answer too

Thank you so much for the help and content created!
I'm saving money to buy the ebook, as I'm Brazilian the price of BRL x EUR is a little expensive, but without a doubt your book will be a great investment for my career!

**Comment by odan** [comment]
>   EntityManager::class => DI\factory(function(ContainerInterface $container): EntityManagerInterface {
        return EntityManagerFactory::create($container);

The factory does not create a new instance for each "call". Just like any other definition, factories are called once and the same result is returned every time the factory needs to be resolved.  This gives you the same result, but with less code:

```php
EntityManager::class => function(ContainerInterface $container) {
    return EntityManagerFactory::create($container);
}
```

> The container.php file is now just with the classes from your tutorial while the dependencies.php will leave the dependencies and interfaces inversions of my project.
> Does it make sense to have this segregation of files?

I think it's a matter of taste. Personally, I would put everything in a single file like container.php or something, because it's not always clear to other people where to put what. this file should never get very big, since most project classes should use [autowiring](https://php-di.org/doc/autowiring.html) anyway. So even in a project with more than 1000 project classes, the DI definition file might never contain more than 50 entries.

**Comment by NicolasPereira** [comment]
Hi @odan ! Thank you so much for all the tips and for solving my doubts!

I hope to one day contribute to the community just like you!

You can close the issue!
