### ISSUE TITLE
Transmit dropdown values to view

### ISSUE THREAD

**Issue by samuelgfeller** [odan/slim4-tutorial#48]
I have `clients` to whom `users` are assigned and they have a `status` . 

Now when querying the client list or just one, I also want to return all user names and ids and status names and ids. 

How would you do that? I have a ClientResult data class that contains aggregates like status name and the name of the assigned user. I thought of adding `array $allStatuses` and `array $allUsers` properties to the result data class. 

But how do I query them, I guess I have no other choice than making a second query to retrieve all statuses and another one for the users for each request. How do I do that in the most efficient way? 

Thinking about it shorty, I think I'd inject the `StatusFinderRepository` and `UserFinderRepository` to the `ClientFinderRepository` class and then populate the `$clientResultData->allStatuses`  and `$clientResultData->allUsers` for the view to access it simply. 
Maybe instead of injecting into `ClientFinderRepository` I could do it on the domain service class `ClientFinder`.

What are your thoughts?

**Comment by odan** [comment]
I think a use case specific query would be much more efficient.

**Comment by samuelgfeller** [comment]
I solved it like this: 

Instead of storing all statuses and users in each ClientResult data class, I created a result collection data class with an array of clients and also statuses and users. This gets then passed to the view as json. 

```php
<?php

namespace App\Domain\Client\Data;

class ClientResultDataCollection
{
    // Collection of clients
    /** @var ClientResultAggregateData[]|null  */
    public ?array $clients = [];

    // View needs all statuses, sexes and users for dropdowns
    public ?array $statuses;
    public ?array $users;
    public ?array $sexes;
}
```

And populated like this in `ClientFinder.php`
```php
$clientResultCollection = new ClientResultDataCollection();
$clientResultCollection->clients = $this->clientFinderRepository->findAllClientsWithResultAggregate();
$clientResultCollection->statuses = $this->clientStatusFinderRepository->findAllStatuses();
// ...
```
