### ISSUE TITLE
Want Query log and Settings access in repository

### ISSUE THREAD

**Issue by sunildabhi** [odan/slim4-tutorial#5]
Hi it's very help full tutorial to me, i have developed many api using your tutorials, thank you very much for such things.

i have two questions

1) Where can i check query log which i have executed in repository.

2) How to get settings in repository

Thanks in advance :)

**Comment by odan** [comment]
Hi @sunildabhi 

1) It depends on the implementation. This is not feature of PDO. If you use the [Laravel Query Builder](https://odan.github.io/2019/12/03/slim4-eloquent.html), you could enable the Query log with `$connection->enableQueryLog();`. If you need it only for debugging, then you could also use the integrated MySQL query logger.

For example:

```php
// Start query logger
$pdo->execute("SET GLOBAL log_output = 'TABLE'; SET GLOBAL general_log = 'ON;");
$pdo->execute("TRUNCATE TABLE mysql.general_log;");

// Do some sql statements...

// Stop query logger
$pdo->execute("SET GLOBAL general_log = 'OFF';");

// Get query log entry
$logs = $pdo->query('SELECT * FROM mysql.general_log;')->fetchAll();
```

2) The settings should be passed from a service to the Repository method. You could also use the [selective/config](https://github.com/selective-php/config#slim-4-integration) component to inject the settings automatically via dependency injection.

**Comment by sunildabhi** [comment]
1) i am using mysql for database connectivity and i want query log in .txt file

2) may i know how to access settings in Service or in Action Class without "selective/config"

```
namespace App\Action;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

final class HomeAction
{
    public function __invoke(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {

        /*want to access custom settings here */

        $response->getBody()->write(json_encode(['success' => true]));

        return $response->withHeader('Content-Type', 'application/json');
    }
}
```

**Comment by odan** [comment]
1) If you want to log the queries into a file just write the result of `$logs = $pdo->query('SELECT * FROM mysql.general_log;')->fetchAll();` into a text file. I would recommend creating a special class or trait to log the queries into a file.

2) The documentation provides an example using dependency injection: https://github.com/selective-php/config#injecting-the-configuration

**Comment by sunildabhi** [comment]
okay it's help me lot, thank you very much for quick response, and such a great tutorials.
