### ISSUE TITLE
[Question] How configure ErrorMiddleware return application/json format

### ISSUE THREAD

**Issue by NicolasPereira** [odan/slim4-tutorial#50]
Hi Odan, how are you?
I'm still working with[ my slim studies project](https://github.com/NicolasPereira/slim-jwt-app) and I'm making an API.
Some application errors (validation, doctrine error and the like) are returning the Slim error screen.
In this case, the name field is required, in the validation I return a throw and the error comes in HTML format

<img width="726" alt="image" src="https://user-images.githubusercontent.com/26687997/175573693-41f88c32-765d-45b9-a811-f4814001bf3a.png">

I would like to know if it is possible to change to return a JSON.
I looked at [Slim's documentation](https://www.slimframework.com/docs/v3/handlers/php-error.html) but I didn't know how to implement it according to the tutorial's structure.
Follows my container.php where the ErrorMiddleware is.
```php
//container.php 

<?php

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ResponseFactoryInterface;
use Selective\BasePath\BasePathMiddleware;
use Slim\App;
use Slim\Factory\AppFactory;
use Slim\Factory\Psr17\Psr17Factory;
use Slim\Middleware\ErrorMiddleware;
use Symfony\Component\Cache\Adapter\ArrayAdapter;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

return [
    'settings' => function () {
        return require __DIR__ . '/settings.php';
    },

    App::class => function (ContainerInterface $container) {
        AppFactory::setContainer($container);

        return AppFactory::create();
    },

    ResponseFactoryInterface::class => function (ContainerInterface $container) {
        return $container->get(Psr17Factory::class);
    },

    ErrorMiddleware::class => function (ContainerInterface $container) {
        $app = $container->get(App::class);
        $settings = $container->get('settings')['error'];
        return new ErrorMiddleware(
            $app->getCallableResolver(),
            $app->getResponseFactory(),
            (bool)$settings['display_error_details'],
            (bool)$settings['log_errors'],
            (bool)$settings['log_error_details']
        );
    },

    BasePathMiddleware::class => function (ContainerInterface $container) {
        return new BasePathMiddleware($container->get(App::class));
    }
];
```
Could you help me or send me articles related to the topic? Thanks

**Comment by odan** [comment]
If you want to dig deeper into this topic, I would recommend reading my blog post and/or my eBook.

* https://odan.github.io/2020/10/18/slim4-cakephp-validation.html
* https://ko-fi.com/s/5f182b4b22

The eBook contains another example using the `symfony/validator` package. 
This Slim 4 - Skeleton contains such an integration:

* https://github.com/odan/slim4-skeleton/blob/master/src/Domain/Customer/Service/CustomerValidator.php

Which validation package you choose is a matter of taste. I would be interested in hearing your feedback what style you prefer.

To catch all ValidationExceptions you need to add a special middleware as shown here or in the blog.

* https://github.com/odan/slim4-skeleton/blob/master/src/Middleware/ValidationExceptionMiddleware.php

**Comment by NicolasPereira** [comment]
Hey odan, thanks for the feedback!
I haven't implemented any validation packages yet, I'm a Laravel developer, I've always used the laravel ecosystem.

At first I wanted to configure the default ErrorMiddleware that you have in your tutorial to return as `json/application`, from what I saw the slim standardizes application errors as `html/text`, wouldn't you be able to change that?

I will read the materials you sent! tks

**Comment by odan** [comment]
You are always in control about the content-type. The custom [DefaultErrorHandler](https://github.com/odan/slim4-skeleton/blob/master/src/Handler/DefaultErrorHandler.php) ensures that all unhandled Exceptions are handled in the same way, to ensure that each error message (with the details) is getting rendered into a very specific JSON format.

**Comment by NicolasPereira** [comment]
Hey ! Tks
I will try to implement what we discussed here in this conversation, thank you very much for your availability!
