### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by mifumo-africa** [odan/slim4-tutorial#53]
I have really struggled to get database to work with this, how or where do you get here

**Comment by odan** [comment]
I don't understand the question. Can you please add more details?

**Comment by odan** [comment]
How to set up a database connection can be found here:

* https://github.com/odan/slim4-skeleton
* https://ko-fi.com/s/5f182b4b22 (eBook)
* https://www.slimframework.com/docs/v4/cookbook/database-doctrine.html
