### ISSUE TITLE
How to use slim-session with this framework

### ISSUE THREAD

**Issue by froschi123** [odan/slim4-tutorial#54]
Hi, i want to make use of the slim-session middleware to manage sessions in slim 
https://github.com/bryanjhv/slim-session

My problem is, i can set session variables in a repository, but how do i read the session variable in another file?

**Comment by odan** [comment]
First, we have different responsibilities here. Usually a repository is for the data(base) access logic. Sessions and session variables are an HTTP request/response specific concern, so they belong to the Action (or Controller in MVC). You can therefore read session variables within your action class (or middleware) and then pass that values into the service class where you need it.

**Comment by froschi123** [comment]
Thanks for the extraordinary fast answer :-) 
you are totally right. I already thought, i am doing something fundamentally wrong here, and your answer pointed it out clearly. Thanks and Cheers
Bernd
