### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by sylainx** [odan/slim4-tutorial#55]
Thank you very much for this amazing article.
I just got to know slim and thanks to your article. I think I'm going to love it.

However I have encountered 2 small problems.

1- When I call the `HomeAction` class I get this error.

![image](https://user-images.githubusercontent.com/74224976/190327417-fad78be0-7d5a-4228-a2f4-485a1d16eb7f.png)

2- Intelliphense tells me that the `getBody` method in `$response->getBody()->write('Hello, World!');` is Undefined

**Comment by odan** [comment]
Can you show the code of your `HomeAction.php` file and the route definition?
