### ISSUE TITLE
404 Slim\Exception\HttpNotFoundException on real shared hosing server 

### ISSUE THREAD

**Issue by ElectroVilla** [odan/slim4-tutorial#57]
First, I'd like to thank you for sharing such useful content and even giving me the opportunity to ask a question, your efforts are highly appreciated.

 I followed your steps to build the "Hello World" server, it worked fine, then I moved to forward and switched off the embedded server, and let the XAMPP do the serving, I got this message (404 Slim\Exception\HttpNotFoundException), same response on a shared hosting server.

Please let me know what the reason is for this problem and how to fix it.

Thank you,
Mina Anton

**Comment by odan** [comment]
Hi!

For Apache (XAMPP) you need to add an internal redirect to the front-controller in `public/index.php`. To achive this you need to add two `.htaccess` files as shown in the [Slim documentation](https://www.slimframework.com/docs/v4/start/web-servers.html#apache-configuration).

You may also set the Slim basePath so that the router can match the URL from the browser with the path set in the route registration. This is done with the setBasePath() method.

```php
$app->setBasePath('/myapp');
```

To dynamically configure the basePath for Slim, I would recommend installing the `BasePathMiddleware`.

* https://github.com/selective-php/basepath#installation

**Comment by ElectroVilla** [comment]
Hi!,

I’d like to thank you very much for your prompt response, I followed the instructions on https://www.slimframework.com/docs/v4/start/web-servers.html#apache-configuration 
But unfortunately, it doesn’t work, it worked properly with a the concept suggested in that link that I have 2 .htaccess files one inside the “public” folder and the other outside it, but the content of the files is as the following:

Inside public folder
```
Options All -Indexes

<Files .htaccess>
order allow,deny
deny from all
</Files>

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Redirect to HTTPS
  # RewriteEngine On
  # RewriteCond %{HTTPS} off
  # RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

  # Some hosts may require you to use the `RewriteBase` directive.
  # Determine the RewriteBase automatically and set it as environment variable.
  # If you are using Apache aliases to do mass virtual hosting or installed the
  # project in a subdirectory, the base path will be prepended to allow proper
  # resolution of the index.php file and to redirect to the correct URI. It will
  # work in environments without path prefix as well, providing a safe, one-size
  # fits all solution. But as you do not need it in this case, you can comment
  # the following 2 lines to eliminate the overhead.
  RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
  RewriteRule ^(.*) - [E=BASE:%1]
  
  # If the above doesn't work you might need to set the `RewriteBase` directive manually, it should be the
  # absolute physical path to the directory that contains this htaccess file.
  # RewriteBase /

  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^ index.php [QSA,L]
  RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

```

Outside the public folder (app root folder)
```
Options All -Indexes

<Files .htaccess>
order allow,deny
deny from all
</Files>

<IfModule mod_rewrite.c>
  # Redirect to the public folder
  RewriteEngine On
  # RewriteBase /
  RewriteRule ^$ public/ [L]
  RewriteRule (.*) public/$1 [L]

  # Redirect to HTTPS
  # RewriteEngine On
  # RewriteCond %{HTTPS} off
  # RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>


```

Now it is working fine, I don’t know why the original code suggested by the slim framework doesn’t work, and what is more surprising is that I made a simple "React" front end and deployed both frontend and backend on two different shared hosting servers.
On one of them, it worked perfectly while on the other it didn't work and because of CORS, it is the same code for both of them.

I don’t know if this is a server issue or a code issue because the CORS appeared on only one hosting server.
Probably I’ll go to the server without issues but if you want to guide me to further instructions (if you think it is a code issue) I’ll be more than happy to read and respond.

Again, I’d like to show my sincere appreciation for your prompt response as it led me to solve my issues.

Best regards,
Mina Anton

**Comment by odan** [comment]
I never had to use such a configuration for XAMPP to get it running, so I cannot reproduce it. Thanks for your feedback.
