### ISSUE TITLE
change route

### ISSUE THREAD

**Issue by carlospizzi** [odan/slim4-tutorial#59]
Hello Daniel!

I am a beginner developer in PHP and Slim and I am following the tutorial.

I need the path to be for example **/api/v1/product/'** instead of **/**

In routes.php I changed the following line:

  $app->get('/', \App\Action\HomeAction::class);

by

  $app->get('/api/v1/product/', \App\Action\HomeAction::class);

When performing the get ( acruxsistemas.api.localhost/api/v1/product/ ), it gives the following error:

404 Not Found, The requested URL was not found on this server.

Can you help me to correct the error?

 Thank you

**Comment by odan** [comment]
To resolve this issue, I would first try to remove the trailing slashes at the end of the url and from the route-definition.

```php
$app->get('/api/v1/product', \App\Action\ProductGetAction::class);
```

Ajax request to: `acruxsistemas.api.localhost/api/v1/product`
