### ISSUE TITLE
Login and logout 

### ISSUE THREAD

**Issue by mkraha** [odan/slim4-tutorial#6]
Hi Odan, Could you please add Login and logout tutorial.? Thank you!!

**Comment by odan** [comment]
Hi @mkraha This [Slim4-Skeleton](https://github.com/odan/slim4-skeleton) contains a session based login and logout example.

**Comment by mkraha** [comment]
> Hi @mkraha This [Slim4-Skeleton](https://github.com/odan/slim4-skeleton) contains a session based login and logout example.
> 
> 
> 
> 

Is that usuable in the production website or just an idea for development purpose?

**Comment by odan** [comment]
Yes this is a working example, also for production.

**Comment by mkraha** [comment]
> Yes this is a working example, also for production.

Thank you.. I will look on it.
