### ISSUE TITLE
Router not working when slim project is inside htdocs/somefolder/slim

### ISSUE THREAD

**Issue by blacktornado** [odan/slim4-tutorial#7]
my web server points to `Htdocs` where all other php projects reside. To open any project in browser we do `10.xxx.xxx.xx:port/somefolder/projectname`
to access this project(Odan skeleton) i am doing the same `10.xxx.xxx.xx:port/somefolder/slim` 

The request lands to `public/index.php` file from there it hits `bootstrap.php` and `container.php` , i just put `echo` on top of every script to check.
Now when it lands to `Router.php` its trying to resolve the route `/` but throwing `404 Not Found` 

`Type: Slim\Exception\HttpNotFoundException`
`code: 404`
`Message: Not Found`
`File: /www/zendphp7/htdocs/somefolder/slim/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php`

to make it work if i remove this line `return function(App $app){` from `router.php` and again add this two lines in `router.php`
`$app = AppFactory::create();`
`$app->setBasePath('/somefolder/slim');`

as said this makes no sense as i am again instantiating the app from router.php and that is a bad design. How to solve this. 

Thanks in advance

**Comment by blacktornado** [comment]
i just found out its the `$app->add(BasePathMiddleware::class) ;`  inside `middleware.php` that is not working, and removing this line and setting `$app->setBasePath('/somefolder/slim');` in `container.php` worked and solved my problem. 

Though i am not 100% convinced as i need to change this everytime i move my app to different environment

**Comment by odan** [comment]
I think the BasePathDetector doesn't return the correct basePath because your directory structure is to deep.

Whats the result of this code?

```php
$basePathDetector = new \Selective\BasePath\BasePathDetector($_SERVER);
$basePath = $basePathDetector->getBasePath();
```

The result shoule be: `/somefolder/slim`

What happens when you put your application one directory above. For example from `/somefolder/slim` to `/somefolder`?

**Comment by blacktornado** [comment]
@odan where do you want me to put this code.
i put it in `middleware.php` and got this error
 `Uncaught TypeError:Argument 1 passed to Selective\BasePath\BasePathMiddleware::construct() must be an instance of Slim\App, array given, `

**Comment by odan** [comment]
You can copy/paste this code where you want, for example in the `config/bootstrap.php` after the composer autoloader. 

Example:

```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

$basePathDetector = new \Selective\BasePath\BasePathDetector($_SERVER);
echo $basePathDetector->getBasePath();

exit;
```

**Comment by blacktornado** [comment]
@odan  i got the same error as it is expecting instance $app and i am passing $_SERVER array

**Comment by odan** [comment]
This is strange. I have tested in on my computer. Have you copied exactly the code from above into `config/bootstrap.php` ?

**Comment by blacktornado** [comment]
@odan sorry it was my bad i didn't copied that rather wrote the code and ran into that error.
but now that i did i am not getting any echo for this statement. it is just blank

`$basePathDetector = new \Selective\BasePath\BasePathDetector($_SERVER);`
`echo $basePathDetector->getBasePath();`

**Comment by odan** [comment]
Ok this is also strange, it should never be blank. What web server do you use? Apache?

**Comment by blacktornado** [comment]
@odan i am using php built in web server with php 7+

**Comment by odan** [comment]
Ok, I guess only for development, right?

Then try this: Open the console and change into the project `public/` directory. Then run:

```
php -S localhost:8000
```

Open your website, e.g. `http://localhost:8000`

https://github.com/selective-php/basepath#php-built-in-webserver-usage
