### ISSUE TITLE
Filepond missing steps

### ISSUE THREAD

**Issue by mkraha** [odan/slim4-tutorial#8]
Hi Odan, Thank you so much for the filepond tutorial for Slim 4.

I think you missed 5 and 6 steps on the proccess in the tutorial.
https://pqina.nl/filepond/docs/patterns/api/server/#process

**Comment by odan** [comment]
Do you have an idea how to solve this?

**Comment by mkraha** [comment]
> Do you have an idea how to solve this?

No but I will try to but for me it will take time.

**Comment by odan** [comment]
I think I found the missing part. The [FilePond article](https://odan.github.io/2020/10/06/slim4-filepond.html) has been updated.

**Comment by odan** [comment]
Does it work for you?

**Comment by mkraha** [comment]
@odan I didn't done yet. i will let you know tomorrow.

**Comment by mkraha** [comment]
@odan Hi..

I did tested 
1. the process upload works but revert is not working because which is not from storage directory but from tmp/upload.
2. question, what about if submit action is different? do i have to use `$this->storeUploadedFiles($submittedIds, $response)` method on form action method?
3. what about following actions, i have to create a method for those?

> restore: 'filepond/restore?id=',
            fetch: 'filepond/fetch?data=',
            load: 'filepond/load',
            fetch: 'filepond/fetch'

**Comment by odan** [comment]
Thanks for testing.

1. It's fixed now. The path settings could / should be loaded from the settings, but everybody does loading the settings a little bit different.
2. The ProcessAction checks whether it is an image upload or a final submit. It can never be both at the same time (as far as I know). You have to do nothing special, because it does this automatically.
3. As I mentioned in the article, these endpoints are not implemented because I only wanted to show the most basic functionality.

**Comment by mkraha** [comment]
Thank you and got it for 1 and 3.

>     2\. The ProcessAction checks whether it is an image upload or a final submit. It can never be both at the same time (as far as I know). You have to do nothing special, because it does this automatically.

I did submit tried with different form action but after upload the file which was in the tmp/upload folder, after submit the file is not moved to storage so that i asked that have to use moveuploadedfiles method on the submit action.

**Comment by odan** [comment]
I have tested the submit button and it should work. 

![image](https://user-images.githubusercontent.com/781074/95678494-49d79b00-0bcd-11eb-9cce-ccf339873cc8.png)

Make sure that you use the same Filepond `server -> process` options on the client-side:

```js
FilePond.setOptions({
        // upload to this server end point
        server: {
              process:(fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
                  // ...
             }
        }
```
