### ISSUE TITLE
Directory structure are incomplete

### ISSUE THREAD

**Issue by antoniogarcia78** [odan/slim4-tutorial#9]
You configure autoload-dev with tests directory but in the structure has not this directory

**Comment by igor-mobapps** [comment]
The `tests folder` is in the directory

![tests folder](https://user-images.githubusercontent.com/58818072/96057339-2297fc80-0e5f-11eb-8799-48b73dcaafd2.png)

**Comment by antoniogarcia78** [comment]
Sorry. I speak about the tutorial and ebook. I recreate the project from zero and not from the skeleton.

**Comment by odan** [comment]
The tutorial does not cover this topic (testing), so the `tests/` directory was not needed there.
